// sample_data.js - Default dataset loaded before user uploads or loads amazon.csv
window.SAMPLE_DATA = [
  {
    product_id: "B07JW9H4J1",
    product_name: "Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12, 11, X, 8, iPad Air",
    category: "Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables",
    discounted_price: 399,
    actual_price: 1099,
    discount_percentage: 64,
    rating: 4.2,
    rating_count: 24269,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51UsScvHQNL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Wayona-Braided-WN3LG1-Syncing-Charging/dp/B07JW9H4J1"
  },
  {
    product_id: "B098NS6PVG",
    product_name: "Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops",
    category: "Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables",
    discounted_price: 199,
    actual_price: 349,
    discount_percentage: 43,
    rating: 4.0,
    rating_count: 43994,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/31zOsqQOAOL._SY445_SX342_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Ambrane-Unbreakable-Charging-Braided-Cable/dp/B098NS6PVG"
  },
  {
    product_id: "B096MSW6CT",
    product_name: "Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12, 11, X, iPad Air",
    category: "Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables",
    discounted_price: 199,
    actual_price: 1899,
    discount_percentage: 90,
    rating: 3.9,
    rating_count: 7928,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/31IvNJZnmdL._SY445_SX342_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Sounce-iPhone-Charging-Compatible-Devices/dp/B096MSW6CT"
  },
  {
    product_id: "B08HDJ86NZ",
    product_name: "boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant Sturdy Cable",
    category: "Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables",
    discounted_price: 329,
    actual_price: 699,
    discount_percentage: 53,
    rating: 4.2,
    rating_count: 94363,
    img_link: "https://m.media-amazon.com/images/I/41V5FtEWPkL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Deuce-300-Resistant-Tangle-Free-Transmission/dp/B08HDJ86NZ"
  },
  {
    product_id: "B08CF3B7N1",
    product_name: "Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone",
    category: "Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables",
    discounted_price: 154,
    actual_price: 399,
    discount_percentage: 61,
    rating: 4.2,
    rating_count: 16905,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/31VzNhhqifL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Portronics-Konnect-POR-1080-Charging-Function/dp/B08CF3B7N1"
  },
  {
    product_id: "B08Y1TFSP6",
    product_name: "pTron Solero TB301 3A Type-C Data and Fast Charging Cable, Made in India, 480Mbps Data Sync",
    category: "Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables",
    discounted_price: 149,
    actual_price: 1000,
    discount_percentage: 85,
    rating: 3.9,
    rating_count: 24871,
    img_link: "https://m.media-amazon.com/images/I/31wOPjcSxlL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Solero-TB301-Charging-480Mbps-1-5-Meter/dp/B08Y1TFSP6"
  },
  {
    product_id: "B008IFXQFU",
    product_name: "TP-Link USB WiFi Adapter for PC (TL-WN725N) N150 Wireless Network Adapter Nano Size",
    category: "Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters",
    discounted_price: 499,
    actual_price: 999,
    discount_percentage: 50,
    rating: 4.2,
    rating_count: 179691,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/31e6ElWRymL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/TP-Link-TL-WN725N-150Mbps-Wireless-Adapter/dp/B008IFXQFU"
  },
  {
    product_id: "B08498H13H",
    product_name: "HP GK320 Wired Full Size RGB Backlight Mechanical Gaming Keyboard, 4 LED Indicators",
    category: "Computers&Accessories|Accessories&Peripherals|PCGamingPeripherals|GamingKeyboards",
    discounted_price: 1519,
    actual_price: 3499,
    discount_percentage: 57,
    rating: 4.3,
    rating_count: 408,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/414js-21FqL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/HP-GK320-Gaming-Keyboard-4QN01AA/dp/B08498H13H"
  },
  {
    product_id: "B08Y7MXFMK",
    product_name: "Offbeat DASH 2.4GHz Wireless + Bluetooth 5.1 Mouse, Multi-Device Dual Mode Slim Rechargeable",
    category: "Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Mice",
    discounted_price: 1099,
    actual_price: 1499,
    discount_percentage: 27,
    rating: 4.2,
    rating_count: 2375,
    img_link: "https://m.media-amazon.com/images/I/31dnZ234ZOL._SY300_SX300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Offbeat-Wireless-Bluetooth-Rechargeable-Adjustable/dp/B08Y7MXFMK"
  },
  {
    product_id: "B09F5Z694W",
    product_name: "Canon E4570 All-in-One Wi-Fi Ink Efficient Colour Printer with FAX/ADF/Duplex Printing",
    category: "Computers&Accessories|Printers,Inks&Accessories|Printers|InkjetPrinters",
    discounted_price: 8349,
    actual_price: 9625,
    discount_percentage: 13,
    rating: 3.8,
    rating_count: 3652,
    img_link: "https://m.media-amazon.com/images/I/41-BRsjrvDL._SY300_SX300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Canon-E4570-Efficient-Printing-Standard/dp/B09F5Z694W"
  },
  {
    product_id: "B07KSMBL2H",
    product_name: "AmazonBasics Flexible Premium HDMI Cable (Black, 4K@60Hz, 18Gbps), 3-Foot",
    category: "Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables",
    discounted_price: 219,
    actual_price: 700,
    discount_percentage: 69,
    rating: 4.4,
    rating_count: 426973,
    img_link: "https://m.media-amazon.com/images/I/41nPYaWA+ML._SY300_SX300_.jpg",
    product_link: "https://www.amazon.in/AmazonBasics-Flexible-HDMI-Cable-3-Foot/dp/B07KSMBL2H"
  },
  {
    product_id: "B08DPLCM6T",
    product_name: "LG 80 cm (32 inches) HD Ready Smart LED TV 32LM563BPTC (Dark Iron Gray)",
    category: "Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions",
    discounted_price: 13490,
    actual_price: 21990,
    discount_percentage: 39,
    rating: 4.3,
    rating_count: 11976,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/51v-2Nzr+ML._SY300_SX300_.jpg",
    product_link: "https://www.amazon.in/LG-inches-Ready-Smart-32LM563BPTC/dp/B08DPLCM6T"
  },
  {
    product_id: "B09F6S8BT6",
    product_name: "Samsung 80 cm (32 Inches) Wondertainment Series HD Ready LED Smart TV UA32T4340BKXXL",
    category: "Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions",
    discounted_price: 13490,
    actual_price: 22900,
    discount_percentage: 41,
    rating: 4.3,
    rating_count: 16299,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51q3+E64azL._SX300_SY300_.jpg",
    product_link: "https://www.amazon.in/Samsung-Inches-Wondertainment-UA32T4340BKXXL-Glossy/dp/B09F6S8BT6"
  },
  {
    product_id: "B0B1YVCJ2Y",
    product_name: "Acer 80 cm (32 inches) I Series HD Ready Android Smart LED TV AR32AR2841HDFL",
    category: "Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions",
    discounted_price: 11499,
    actual_price: 19990,
    discount_percentage: 42,
    rating: 4.3,
    rating_count: 4703,
    img_link: "https://m.media-amazon.com/images/I/41gikeSuhAL._SY300_SX300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Acer-inches-Ready-Android-AR32AR2841HDFL/dp/B0B1YVCJ2Y"
  },
  {
    product_id: "B08B42LWKN",
    product_name: "OnePlus 80 cm (32 inches) Y Series HD Ready LED Smart Android TV 32Y1 (Black)",
    category: "Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions",
    discounted_price: 14999,
    actual_price: 19999,
    discount_percentage: 25,
    rating: 4.2,
    rating_count: 34899,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/41WE9ZGEC4L._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/OnePlus-inches-Ready-Android-32Y1/dp/B08B42LWKN"
  },
  {
    product_id: "B0B15CPR37",
    product_name: "Samsung 108 cm (43 inches) Crystal 4K Neo Series Ultra HD Smart LED TV UA43AUE65AKXXL",
    category: "Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions",
    discounted_price: 32990,
    actual_price: 47900,
    discount_percentage: 31,
    rating: 4.3,
    rating_count: 7109,
    img_link: "https://m.media-amazon.com/images/I/41Tz1YnJkoL._SY300_SX300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Samsung-inches-Crystal-Ultra-UA43AUE65AKXXL/dp/B0B15CPR37"
  },
  {
    product_id: "B09RFC46VP",
    product_name: "Redmi 108 cm (43 inches) 4K Ultra HD Android Smart LED TV X43 | L43R7-7AIN",
    category: "Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions",
    discounted_price: 26999,
    actual_price: 42999,
    discount_percentage: 37,
    rating: 4.2,
    rating_count: 45238,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/41w1didcczL._SY300_SX300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Redmi-inches-Ultra-Android-L43R7-7AIN/dp/B09RFC46VP"
  },
  {
    product_id: "B07B275VN9",
    product_name: "Airtel DigitalTV DTH Television, Setup Box Remote Compatible for SD and HD Recording",
    category: "Electronics|HomeTheater,TV&Video|Accessories|RemoteControls",
    discounted_price: 179,
    actual_price: 799,
    discount_percentage: 78,
    rating: 3.7,
    rating_count: 2201,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/41v00lhhdbL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Airtel-Digital-Remote-Compatible-Recording/dp/B07B275VN9"
  },
  {
    product_id: "B08VS3YLRK",
    product_name: "Portronics Adapto 20 Type C 20W Fast PD Adapter Charger with Fast Charging for iPhone & iPad",
    category: "Electronics|Mobiles&Accessories|MobileAccessories|Chargers|WallChargers",
    discounted_price: 529,
    actual_price: 1499,
    discount_percentage: 65,
    rating: 4.1,
    rating_count: 8599,
    img_link: "https://m.media-amazon.com/images/I/31wqydqbA9L._SX300_SY300_QL70_ML2_.jpg",
    product_link: "https://www.amazon.in/Portronics-Adapto-Adapter-Charger-Charging/dp/B08VS3YLRK"
  },
  {
    product_id: "B0B4F3QNDM",
    product_name: "Samsung Galaxy M13 5G (Aqua Green, 6GB, 128GB Storage) | 5000mAh Battery",
    category: "Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones",
    discounted_price: 13999,
    actual_price: 19499,
    discount_percentage: 28,
    rating: 4.1,
    rating_count: 18998,
    img_link: "https://m.media-amazon.com/images/I/413sCRKobNL._SX300_SY300_QL70_ML2_.jpg",
    product_link: "https://www.amazon.in/Samsung-Galaxy-Storage-5000mAh-Battery/dp/B0B4F3QNDM"
  },
  {
    product_id: "B07GQD4K6L",
    product_name: "boAt Bassheads 100 in Ear Wired Earphones with Mic (Furious Red)",
    category: "Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear",
    discounted_price: 379,
    actual_price: 999,
    discount_percentage: 62,
    rating: 4.1,
    rating_count: 363713,
    img_link: "https://m.media-amazon.com/images/I/31qVddHyy5L._SX300_SY300_QL70_ML2_.jpg",
    product_link: "https://www.amazon.in/Boat-BassHeads-100-Inspired-Earphones/dp/B07GQD4K6L"
  },
  {
    product_id: "B07WDKLRM4",
    product_name: "iQOO Z6 44W by vivo (Lumina Blue, 4GB RAM, 128GB Storage) | 6.44 AMOLED Display",
    category: "Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones",
    discounted_price: 13999,
    actual_price: 19999,
    discount_percentage: 30,
    rating: 4.1,
    rating_count: 19252,
    img_link: "https://m.media-amazon.com/images/I/41iVkyHeTUL._SX300_SY300_QL70_ML2_.jpg",
    product_link: "https://www.amazon.in/iQOO-Lumina-Blue-128GB-Storage/dp/B07WDKLRM4"
  },
  {
    product_id: "B0BP18W8TM",
    product_name: "Fire-Boltt Gladiator 1.96 Biggest Display Smart Watch with Bluetooth Calling & 123 Sports Modes",
    category: "Electronics|WearableTechnology|SmartWatches",
    discounted_price: 3999,
    actual_price: 9999,
    discount_percentage: 60,
    rating: 4.4,
    rating_count: 73,
    img_link: "https://m.media-amazon.com/images/I/51vHAEYKeWL._SX300_SY300_QL70_ML2_.jpg",
    product_link: "https://www.amazon.in/Fire-Boltt-Gladiator-Bluetooth-Assistant-Interactions/dp/B0BP18W8TM"
  },
  {
    product_id: "B07GXHC691",
    product_name: "STRIFF PS2 Multi Angle Mobile/Tablet Tabletop Stand Phone Holder Portable Foldable",
    category: "Electronics|Mobiles&Accessories|MobileAccessories|Stands",
    discounted_price: 99,
    actual_price: 499,
    discount_percentage: 80,
    rating: 4.3,
    rating_count: 42641,
    img_link: "https://m.media-amazon.com/images/I/31iE517+NFL._SY300_SX300_.jpg",
    product_link: "https://www.amazon.in/STRIFF-Mobile-Android-Samsung-OnePlus/dp/B07GXHC691"
  },
  {
    product_id: "B08FN6WGDQ",
    product_name: "Samsung Galaxy Buds Live Bluetooth Truly Wireless in Ear Earbuds with Mic, Mystic Black",
    category: "Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear",
    discounted_price: 4790,
    actual_price: 15990,
    discount_percentage: 70,
    rating: 4.0,
    rating_count: 4390,
    img_link: "https://m.media-amazon.com/images/I/31Sx7+mu+vL._SY300_SX300_.jpg",
    product_link: "https://www.amazon.in/Samsung-Galaxy-SM-R180NZKAINU-Mystic-Black/dp/B08FN6WGDQ"
  },
  {
    product_id: "B0B3D39RKV",
    product_name: "OnePlus Nord 2T 5G (Jade Fog, 12GB RAM, 256GB Storage) MediaTek Dimensity 1300",
    category: "Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones",
    discounted_price: 33999,
    actual_price: 33999,
    discount_percentage: 0,
    rating: 4.3,
    rating_count: 17415,
    img_link: "https://m.media-amazon.com/images/I/41iEc0hf6TL._SX300_SY300_QL70_ML2_.jpg",
    product_link: "https://www.amazon.in/OnePlus-Nord-Jade-256GB-Storage/dp/B0B3D39RKV"
  },
  {
    product_id: "B086Q3QMFS",
    product_name: "Classmate Drawing Book - Unruled, 40 Pages, 210 mm x 297 mm - Pack Of 4",
    category: "OfficeProducts|OfficePaperProducts|Paper|Stationery|Notebooks,WritingPads&Diaries|CompositionNotebooks",
    discounted_price: 120,
    actual_price: 120,
    discount_percentage: 0,
    rating: 4.5,
    rating_count: 4951,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/41KFL-3kiUL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Classmate-Drawing-Book-Unruled-Pages/dp/B086Q3QMFS"
  },
  {
    product_id: "B07LFQLKFZ",
    product_name: "Parker Moments Vector Timecheck Gold Trim Roller Ball Pen (Black)",
    category: "OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|LiquidInkRollerballPens",
    discounted_price: 420,
    actual_price: 420,
    discount_percentage: 0,
    rating: 4.2,
    rating_count: 1926,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/31-wcLwDaBL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Parker-Moments-Vector-Timecheck-Roller/dp/B07LFQLKFZ"
  },
  {
    product_id: "B00LY17RHI",
    product_name: "Camlin Elegante Fountain Pen - Black/Blue/Red Handcrafted with Gold Plated Nib",
    category: "OfficeProducts|OfficePaperProducts|Paper|Stationery|Pens,Pencils&WritingSupplies|Pens&Refills|FountainPens",
    discounted_price: 225,
    actual_price: 225,
    discount_percentage: 0,
    rating: 4.1,
    rating_count: 4798,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/21C8ziy-IJL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Camlin-Elegante-Fountain-Pen-Black/dp/B00LY17RHI"
  },
  {
    product_id: "B09SPTNG58",
    product_name: "Crompton Sea Sapphira 1200 mm Ultra High Speed 3 Blade Ceiling Fan (Lustre Brown)",
    category: "Home&Kitchen|Heating,Cooling&AirQuality|Fans|CeilingFans",
    discounted_price: 1449,
    actual_price: 2349,
    discount_percentage: 38,
    rating: 3.9,
    rating_count: 9019,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/31pRaPCFqVL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/CROMPTON-Sapphira-Ultra-Ceiling-Lustre/dp/B09SPTNG58"
  },
  {
    product_id: "B083J64CBB",
    product_name: "Kuber Industries Waterproof Canvas Laundry Bag/Hamper Foldable Bin 45L Capacity",
    category: "Home&Kitchen|HomeStorage&Organization|LaundryOrganization|LaundryBaskets",
    discounted_price: 199,
    actual_price: 499,
    discount_percentage: 60,
    rating: 4.0,
    rating_count: 10234,
    img_link: "https://m.media-amazon.com/images/I/51YNXPOgNML._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Kuber-Industries-Waterproof-Organizer-CTKTC034616/dp/B083J64CBB"
  },
  {
    product_id: "B08JV91JTK",
    product_name: "JM SELLER 180 W Electric Beater High Speed Hand Mixer Egg Beater for Cake Making",
    category: "Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandMixers",
    discounted_price: 474,
    actual_price: 1299,
    discount_percentage: 64,
    rating: 4.1,
    rating_count: 550,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/41V4DpKc7sL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/JM-SELLER-Electric-Beater-180-Watt/dp/B08JV91JTK"
  },
  {
    product_id: "B0BQ3K23Y1",
    product_name: "Oratech Coffee Frother electric, milk frother electric cappuccino maker",
    category: "Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandBlenders",
    discounted_price: 279,
    actual_price: 499,
    discount_percentage: 44,
    rating: 4.8,
    rating_count: 28,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/41t3WVUlRmL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Oratech-electric-cappuccino-Mocktail-Multicolour/dp/B0BQ3K23Y1"
  },
  {
    product_id: "B09MT94QLL",
    product_name: "Havells Glaze 74W Pearl Ivory Gold Ceiling Fan Sweep: 1200 Mm",
    category: "Home&Kitchen|Heating,Cooling&AirQuality|Fans|CeilingFans",
    discounted_price: 1999,
    actual_price: 4775,
    discount_percentage: 58,
    rating: 4.2,
    rating_count: 1353,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/21SHZOWOynL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Havells-Glaze-Pearl-Ivory-Ceiling/dp/B09MT94QLL"
  },
  {
    product_id: "B07NKNBTT3",
    product_name: "Pick Ur Needs Lint Remover for Clothes High Range Rechargeable Lint Shaver",
    category: "Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|LintShavers",
    discounted_price: 799,
    actual_price: 1230,
    discount_percentage: 35,
    rating: 4.1,
    rating_count: 2138,
    img_link: "https://m.media-amazon.com/images/I/419vF7uEFEL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Ur-NeedsTM-Rocklight-Remover-Fabric/dp/B07NKNBTT3"
  },
  {
    product_id: "B09KPXTZXN",
    product_name: "Rico Japanese Technology Rechargeable Wireless Electric Chopper 250 ML 30 Watts",
    category: "Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MiniFoodProcessors&Choppers",
    discounted_price: 949,
    actual_price: 1999,
    discount_percentage: 53,
    rating: 4.0,
    rating_count: 1679,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/41JnGOKI2dL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Rico-Japanese-Technology-Rechargeable-Replacement/dp/B09KPXTZXN"
  },
  {
    product_id: "B078HG2ZPS",
    product_name: "Butterfly Smart Wet Grinder 2L (White) with Coconut Scrapper Attachment 150 W",
    category: "Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|Mills&Grinders|WetGrinders",
    discounted_price: 3657.66,
    actual_price: 5156,
    discount_percentage: 29,
    rating: 3.9,
    rating_count: 12837,
    img_link: "https://m.media-amazon.com/images/I/414JLnTlLnL._SY300_SX300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Butterfly-150-Watt-Grinder-Scrapper-Attachment/dp/B078HG2ZPS"
  },
  {
    product_id: "B07N2MGB3G",
    product_name: "AGARO Marvel 9 Liters Oven Toaster Griller, Cake Baking OTG (Black)",
    category: "Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|OvenToasterGrills",
    discounted_price: 1699,
    actual_price: 1999,
    discount_percentage: 15,
    rating: 4.1,
    rating_count: 8873,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/41LKiR8QpwL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/AGARO-Marvel-Litre-Toaster-Griller/dp/B07N2MGB3G"
  },
  {
    product_id: "B008LN8KDM",
    product_name: "Philips GC1920/28 1440-Watt Non-Stick Soleplate Steam Iron Pink",
    category: "Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|SteamIrons",
    discounted_price: 1849,
    actual_price: 2095,
    discount_percentage: 12,
    rating: 4.3,
    rating_count: 7681,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/41sKyiPWzAL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Philips-GC1920-28-1440-Watt-Non-Stick/dp/B008LN8KDM"
  },
  {
    product_id: "B08MZNT7GP",
    product_name: "Havells OFR 13 Wave Fin with PTC Fan Heater 2900 Watts (Black)",
    category: "Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|FanHeaters",
    discounted_price: 12499,
    actual_price: 19825,
    discount_percentage: 37,
    rating: 4.1,
    rating_count: 322,
    img_link: "https://m.media-amazon.com/images/I/41Dp3g8y8sL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Havells-OFR-13-Wave-Fin/dp/B08MZNT7GP"
  },
  {
    product_id: "B009P2L7CO",
    product_name: "Bajaj DHX-9 1000W Heavy Weight Dry Iron with Advance Soleplate Technology",
    category: "Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons",
    discounted_price: 1099,
    actual_price: 1920,
    discount_percentage: 43,
    rating: 4.2,
    rating_count: 9772,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/411ZPXAMTlL._SY300_SX300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Bajaj-DHX-1000-Watt-Ivory-Color/dp/B009P2L7CO"
  },
  {
    product_id: "B07YC8JHMB",
    product_name: "Aquasure From Aquaguard Amaze RO+UV+MTDS 7L Storage Water Purifier Eureka Forbes",
    category: "Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterFilters&Purifiers",
    discounted_price: 8199,
    actual_price: 16000,
    discount_percentage: 49,
    rating: 3.9,
    rating_count: 18497,
    img_link: "https://m.media-amazon.com/images/I/31Gulp0B-0L._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Eureka-Forbes-Amaze-RO-MTDS/dp/B07YC8JHMB"
  },
  {
    product_id: "B08N6P8G5K",
    product_name: "INALSA Air Fryer Digital 4L Nutri Fry 1400W Smart AirCrisp Touch Control",
    category: "Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|DeepFatFryers|AirFryers",
    discounted_price: 6790,
    actual_price: 10995,
    discount_percentage: 38,
    rating: 4.5,
    rating_count: 3192,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/41vooC+8vUL._SY300_SX300_.jpg",
    product_link: "https://www.amazon.in/Inalsa-Digital-Fryer-Nutri-Fry/dp/B08N6P8G5K"
  },
  {
    product_id: "B08J7VCT12",
    product_name: "KENT 16068 Zoom Vacuum Cleaner Cordless Hoseless Rechargeable HEPA Filters 130 W",
    category: "Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|Vacuums|HandheldVacuums",
    discounted_price: 6999,
    actual_price: 14999,
    discount_percentage: 53,
    rating: 4.1,
    rating_count: 1728,
    img_link: "https://m.media-amazon.com/images/I/31B24fjfiTL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Kent-Zoom-Vacuum-Cleaner-16068/dp/B08J7VCT12"
  },
  {
    product_id: "B0BJYSCWFQ",
    product_name: "Kitchengenix Mini Waffle Maker 4 Inch 350 Watts Stainless Steel Non-Stick",
    category: "Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|WaffleMakers&Irons",
    discounted_price: 899,
    actual_price: 1999,
    discount_percentage: 55,
    rating: 4.2,
    rating_count: 39,
    img_link: "https://m.media-amazon.com/images/I/41wOaCtfCZL._SY300_SX300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Kitchengenixs-Waffle-Maker-Inch-Watts/dp/B0BJYSCWFQ"
  },
  {
    product_id: "B0187F2IOK",
    product_name: "Bajaj HM-01 Powerful 250W Hand Mixer Black Chromeplated Dough Beater",
    category: "Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|HandMixers",
    discounted_price: 1499,
    actual_price: 2199,
    discount_percentage: 32,
    rating: 4.4,
    rating_count: 6531,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/31gr8xzOhEL._SX300_SY300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Bajaj-HM-01-250-Watt-Mixer/dp/B0187F2IOK"
  },
  {
    product_id: "B07K19NYZ8",
    product_name: "Usha Hc 812 T Thermo Fan Room Heater Heat Convector",
    category: "Home&Kitchen|Heating,Cooling&AirQuality|RoomHeaters|FanHeaters",
    discounted_price: 2320,
    actual_price: 3290,
    discount_percentage: 29,
    rating: 3.8,
    rating_count: 195,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/41UHdKluMBL._SY300_SX300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/Usha-812-Thermo-Room-Heater/dp/B07K19NYZ8"
  },
  {
    product_id: "B08ZXZ362Z",
    product_name: "akiara - Makes life easy Mini Sewing Machine for Home Tailoring use with Sewing Kit",
    category: "Home&Kitchen|Kitchen&HomeAppliances|SewingMachines&Accessories|Sewing&EmbroideryMachines",
    discounted_price: 1563,
    actual_price: 3098,
    discount_percentage: 50,
    rating: 3.5,
    rating_count: 2283,
    img_link: "https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/51WNhYBloRL._SY300_SX300_QL70_FMwebp_.jpg",
    product_link: "https://www.amazon.in/akiara-Tailoring-Stitching-Scissors-Accessories/dp/B08ZXZ362Z"
  }
];
